### ISSUE TITLE
Duplicate code in library files - potential refactor needed

### ISSUE THREAD

**Issue by FoamyGuy** [adafruit/Adafruit_CircuitPython_Display_Text#125]
actions failure with details on duplicated sections is [here](https://github.com/adafruit/Adafruit_CircuitPython_Display_Text/runs/2017909871?check_suite_focus=true#step:11:31)

We want to avoid having duplicated code if possible. One way to avoid it here will be to make a `LabelBase` class in `__init__.py` with the duplicated parts and extend that in the other types of labels.

**Comment by jposada202020** [comment]
I I took a look at this yesterday. For simple modules, I had success creating  LabelBase, in the __init__ file, then creating new classes the label and bitmap_label as children of display.Group and LabelBase. The setter and the getter needs to be equal in order to use them, however this could be solved using a belonging flag and change the module behavior. However, for some modules although equal, ie background (color and calculation) the way both libraries do some calculations, is different, and calling methods inside them also, complicating things inside LabelBase . A first glance I did not see any "easy" path for this

I see as the possible `easy` to share in the BaseLabel the following modules
* anchored_position
* background_color
* _get_ascent_descent

Bitmap_label is known to save memory, we would need to keep this feature in doing this change as some people have bitmap_label in their projects to save memory.

**Comment by FoamyGuy** [comment]
I will work on this some tonight or tomorrow as well.

Unfortunately I think we may need to get this sorted before we can merge the other PRs because this will cause actions to fail currently.

**Comment by jposada202020** [comment]
@FoamyGuy thanks, Agree, we will work on this, let me know if you want that we do a little brainstorm session.

**Comment by FoamyGuy** [comment]
@jposada202020 I'm going to be working on this some tonight starting in a little bit. If you are around and still interested in brainstorm session ping me on Discord.

**Comment by jposada202020** [comment]
@FoamyGuy working in the turning text. Enclosed is a prototype that uses the internal machine of label

https://github.com/jposada202020/sandbox_display_text/blob/0e4257dde2899ad269f30510668780d66536275f/developing_turning_text.py

![image](https://user-images.githubusercontent.com/34255413/110195484-4c9c8c00-7e0b-11eb-92d6-3810e8663aa8.png)

will wait in your findings..
